POST http://localhost:3003/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkViaWRhaiIsImlkIjoiNjI0Mjk2ZWQyMTNlOGI0ZTdmOWRiZDU1IiwiaWF0IjoxNjUxMzQ5NjA0LCJleHAiOjE2NTEzNTMyMDR9.mvIx20MSoVKFVXG2KTzpgC3CR90nSJJPIN7B3zGYoCg
Content-Type: application/json

{
    "title": "Title of a newer post",
    "author": "Ebidaj",
    "url": "http://localhost/post-url",
    "likes": 144
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "author": "Ebidaj",
    "likes": 3
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkViaWRhaiIsImlkIjoiNjI0Mjk2ZWQyMTNlOGI0ZTdmOWRiZDU1IiwiaWF0IjoxNjUxMzQ5NjA0LCJleHAiOjE2NTEzNTMyMDR9.mvIx20MSoVKFVXG2KTzpgC3CR90nSJJPIN7B3zGYoCg
Content-Type: application/json

{
    "title": "Here's a newer post",
    "author": "Ebidaj",
    "url": "http://localhost/post-url",
    "likes": 12
}

###

POST http://localhost:3003/api/blogs/6268445fda8f4264272fedfb/comments HTTP/1.1
Content-Type: application/json

{
    "comment": "This is another test comment."
}
