POST http://localhost:3003/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkViaWRhaiIsImlkIjoiNjI0MjE0MTRiZDJjZDE5OWI2YzlmNmMwIiwiaWF0IjoxNjQ4NTIyMTY2LCJleHAiOjE2NDg1MjU3NjZ9._cTC33Q8e3jck0k3chmaSBrZN0MgFxN2fVsTJJUi2zM
Content-Type: application/json

{
    "title": "Title of a newer post",
    "author": "Ebidaj",
    "url": "http://localhost/post-url",
    "likes": 144
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "author": "Ebidaj",
    "likes": 3
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkViaWRhaiIsImlkIjoiNjI0MjE0MTRiZDJjZDE5OWI2YzlmNmMwIiwiaWF0IjoxNjQ4NTIyMTY2LCJleHAiOjE2NDg1MjU3NjZ9._cTC33Q8e3jck0k3chmaSBrZN0MgFxN2fVsTJJUi2zM
Content-Type: application/json

{
    "title": "Here's a newer post",
    "author": "Ebidaj",
    "url": "http://localhost/post-url",
    "likes": 12
}
